<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <OutputType>Library</OutputType>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>neXn.BlockMatrix.Wpf</RootNamespace>
    <AssemblyName>neXn.BlockMatrix.Wpf</AssemblyName>
    <Version>1.0.2</Version>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <Authors>Dante Wackermann</Authors>
    <NoWarn>1701;1702;IDE0063</NoWarn>
  </PropertyGroup>

</Project>